DROP TABLE IF EXISTS CURRENCY_EXCHANGE;

CREATE TABLE CURRENCY_EXCHANGE(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  currency_from VARCHAR(255) NOT NULL,
  currency_to VARCHAR(255) NOT NULL,
  CONVERSION_MULTIPLE DECIMAL(38,2) NOT NULL,
  ENVIRONMENT VARCHAR(255) NOT NULL
)